#!/bin/bash

connection=""  
connected="false"

if [ -f /var/run/ppp0.pid ]; then
    connected="true"
fi

if [ -f /tmp/rasconnections ]; then
        connection=`head -n1 /tmp/rasconnections`
fi

if [ "${2,,}" == "rasdial" ] && [ "${3,,}" == "/disconnect" ]; then
    echo "Command completed successfully."
    ppp-off
    exit 0
fi 

if [ "${2,,}" == "rasdial" ] && [ "${3,,}" != "" ] && [ "${4,,}" == "/d" ]; then

    if [ "${connection,,}" != "${3,,}"  ]; then
       echo "You are not connected to "${3^^}"."
       echo "Command completed successfully."
       exit 0
    fi
    ppp-off
    exit 0
fi 

if [ "${2,,}" == "rasdial" ] && [ "${3,,}" != "" ] && [ "${4,,}" == "/disconnect" ]; then

    if [ "${connection,,}" != "${3,,}"  ]; then
       echo "You are not connected to "${3^^}"."
       echo "Command completed successfully."
       exit 0
    fi

    echo "Command completed successfully."
    ppp-off
    exit 0
fi 

if [ "${2,,}" == "rasdial" ] && [ "${3,,}" == "" ]; then
     if [ $connected == "true" ]; then
        echo "Connected to "${connection^^}
     else
        echo "No connections"
      fi
exit 0
fi 


if [ "${2,,}" == "rasdial" ] && [ "${3,,}" != "" ]; then

    if [ ! -f /usr/local/chat-scripts/${3,,} ]; then
        echo "Remote Access error 623 - The system could not find the phone book entry for this connection."
    exit 0
    fi

    echo "Connecting to "${3^^}" ..."

    if [ $connected == "true" ]; then

         if [ "${connection,,}" == "${3,,}"  ]; then
            echo "Successfully connected to "${connection^^}"."
            echo "Command completed successfully."
        else
            echo "Remote Access error 633 - The modem (or other connecting device) is already in use or is not configured properly."
        fi
        exit 0
    fi

    ppp-on ${3,,}
    SECONDS=0
    start=$SECONDS
    end=$((start+60))
    while [  $end -gt $SECONDS ] && [ ! -f "/var/run/ppp0.pid" ]; do
         :
     done
     
    if [  -f "/var/run/ppp0.pid" ]; then
        echo "${3,,}" > /tmp/rasconnections
        echo "Verifying username and password..."
        sleep 3s
        echo "Registering your computer on the network..." 
        sleep 3s       
        echo "Successfully connected to "${3^^}
        sleep 5s
        echo "Command completed successfully."
    else
        echo "Remote Access error 635 - An unknown error has occured."
    fi
      
fi